import Database from "better-sqlite3";
import { existsSync } from "node:fs";

interface ActivityRow {
  id: number;
  timestamp: string;
  event: string;
  sender: string;
  receiver: string | null;
  summary: string;
  detail: string | null;
}

const PALETTE = [
  "#58a6ff", "#3fb950", "#d29922", "#f85149",
  "#bc8cff", "#79c0ff", "#56d364", "#e3b341",
];

function agentColor(name: string, map: Map<string, string>): string {
  if (map.has(name)) return map.get(name)!;
  const color = PALETTE[map.size % PALETTE.length];
  map.set(name, color);
  return color;
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

export function exportChat(dbPath: string, opts: { from?: string; to?: string }): string {
  if (!existsSync(dbPath)) {
    return generateHtml([], "No activity database found.");
  }

  const db = new Database(dbPath, { readonly: true });
  let query = "SELECT * FROM activity";
  const conditions: string[] = [];
  const params: string[] = [];

  if (opts.from) {
    conditions.push("timestamp >= ?");
    params.push(opts.from);
  }
  if (opts.to) {
    conditions.push("timestamp <= ?");
    params.push(opts.to);
  }

  if (conditions.length) {
    query += " WHERE " + conditions.join(" AND ");
  }
  query += " ORDER BY timestamp ASC, id ASC";

  const rows = db.prepare(query).all(...params) as ActivityRow[];
  db.close();

  if (rows.length === 0) {
    return generateHtml([], "No messages in this time range.");
  }

  return generateHtml(rows);
}

function generateHtml(rows: ActivityRow[], emptyMsg?: string): string {
  const colorMap = new Map<string, string>();
  const messages = rows.map(row => {
    const senderColor = agentColor(row.sender, colorMap);
    const time = row.timestamp.slice(11, 16); // HH:MM
    const date = row.timestamp.slice(0, 10);
    const content = escapeHtml(row.summary);
    const eventIcon = row.event === "tool_call" ? "🔧" : row.event === "task_update" ? "📋" : "";
    const receiver = row.receiver ? ` → <span style="color:${agentColor(row.receiver, colorMap)}">${escapeHtml(row.receiver)}</span>` : "";

    return `<div class="msg">
  <div class="meta">
    <span class="time">${date} ${time}</span>
    <span class="sender" style="color:${senderColor}">${eventIcon}${escapeHtml(row.sender)}</span>${receiver}
  </div>
  <div class="content">${content}</div>
</div>`;
  }).join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>AgEnD Chat Export</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { background: #0d1117; color: #c9d1d9; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', monospace; padding: 16px; max-width: 900px; margin: 0 auto; }
  h1 { font-size: 18px; color: #58a6ff; padding: 12px 0; border-bottom: 1px solid #21262d; margin-bottom: 16px; }
  .empty { color: #8b949e; padding: 24px; text-align: center; }
  .msg { padding: 8px 12px; margin: 4px 0; border-radius: 6px; background: #161b22; border-left: 3px solid #30363d; }
  .meta { font-size: 12px; margin-bottom: 4px; }
  .time { color: #8b949e; margin-right: 8px; }
  .sender { font-weight: 600; }
  .content { font-size: 14px; line-height: 1.5; white-space: pre-wrap; word-break: break-word; }
  .legend { display: flex; gap: 16px; flex-wrap: wrap; padding: 8px 0; margin-bottom: 12px; font-size: 12px; }
  .legend-item { display: flex; align-items: center; gap: 4px; }
  .legend-dot { width: 10px; height: 10px; border-radius: 50%; }
</style>
</head>
<body>
<h1>AgEnD Chat Export</h1>
${emptyMsg ? `<div class="empty">${escapeHtml(emptyMsg)}</div>` : ""}
${rows.length > 0 ? `<div class="legend">${[...colorMap.entries()].map(([name, color]) => `<div class="legend-item"><div class="legend-dot" style="background:${color}"></div>${escapeHtml(name)}</div>`).join("")}</div>` : ""}
${messages}
<div style="color:#8b949e;font-size:11px;padding:16px 0;text-align:center;">Generated by AgEnD &middot; ${rows.length} messages &middot; ${new Date().toISOString().slice(0, 19)}</div>
</body>
</html>`;
}
